name: .NET

on:
  push:
    branches: [ "8.0" ]
  pull_request:
    branches: [ "8.0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          3.1.x
          4.5.x
          4.8.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: MySQL.Data
    - name: Build
      run: dotnet build --no-restore
      working-directory: MySQL.Data
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: MySQL.Data
    - name: Package
      run: dotnet pack --no-restore --configuration 'Release' 
      working-directory: MySQL.Data
