name: .NET

on:
  push:
    branches: [ "8.0" ]
  pull_request:
    branches: [ "8.0" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          3.1.x
    - name: Authenticate nuget
      run: dotnet nuget add source --username felipmiguel --password ${{ secrets.PACKAGE_PAT }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/felipmiguel/index.json"
      working-directory: MySQL.Data\src
    - name: Restore dependencies
      run: dotnet restore
      working-directory: MySQL.Data
    - name: Build
      run: dotnet build --no-restore
      working-directory: MySQL.Data
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    #   working-directory: MySQL.Data
    - name: Package
      run: dotnet pack --no-restore --configuration 'Release'
      working-directory: MySQL.Data\src
    - name: Publish package
      run: dotnet nuget push "bin\Release\MySql.Data.8.0.30.1.nupkg" --source "github" --api-key ${{ secrets.PACKAGE_PAT }} --skip-duplicate
      working-directory: MySQL.Data\src
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: EFCore
    - name: Build
      run: dotnet build --no-restore
      working-directory: EFCore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    #   working-directory: MySQL.Data
    - name: Package
      run: dotnet pack --no-restore --configuration 'Release'
      working-directory: EFCore\src
    - name: Publish package
      run: dotnet nuget push "bin\Release\MySql.EntityFrameworkCore.3.1.24.nupkg" --source "github" --api-key ${{ secrets.PACKAGE_PAT }} --skip-duplicate
      working-directory: EFCore\src
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: EFCore6
    - name: Build
      run: dotnet build --no-restore
      working-directory: EFCore6
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    #   working-directory: MySQL.Data
    - name: Package
      run: dotnet pack --no-restore --configuration 'Release'
      working-directory: EFCore6\src
    - name: Publish package
      run: dotnet nuget push "bin\Release\MySql.EntityFrameworkCore.6.0.4.nupkg" --source "github" --api-key ${{ secrets.PACKAGE_PAT }} --skip-duplicate
      working-directory: EFCore6\src
    
